### ISSUE TITLE
Cannot install on VSCode 1.13.0

### ISSUE THREAD

**Issue by apobekiaris** [tintoy/msbuild-project-tools-vscode#10]
Hi

I get Counldn't find a compatible version of MSBuild project tools with this version of Code

**Comment by tintoy** [comment]
Hey, sorry to hear you're having problems - the extension currently requires VSCode v1.14 or above (the current stable version of VSCode is 1.16). Is there anything that blocks you from upgrading to the current version of VSCode? If so, I could try lowering the minimum version to 1.13 but I might need your help testing the result.

**Comment by apobekiaris** [comment]
no problem it looks like that I thought I was on the latest but I was outdated. VsCode is a great tool, but those continuous updates are very annoying and forgot that I disabled them.

**Comment by tintoy** [comment]
I know what you mean - kinda makes me feel guilty when I put out an extension update :)
