### ISSUE TITLE
Support for Microsoft.Build.CentralPackageVersions

### ISSUE THREAD

**Issue by loligans** [tintoy/msbuild-project-tools-vscode#103]
It would be very nice if completion information could be provided for projects that use: `Microsoft.Build.CentralPackageVersions` and its `Packages.props` file.

Project location here: https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions

- How it works is when you define a: `Directory.Build.targets`
- You add the Central Package Management Package to the `Directory.Build.targets`  
```xml
<Project>
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />
</Project>
```
- Then create a `Packages.props`
- Add your packages (Note: the usage of the `Update` attribute. I am unable to get completion information from this `PackageReference` when there is no `Include` attribute. In addition, `GlobalPackageReference` properties do not provide completions either. As an aside: when I do provide an `Include` attribute, MSBuild does provide completion information):
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <ItemGroup>
        <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.5.109" PrivateAssets="all" />
        <PackageReference Update="System.Text.Json" Version="6.0.5" />
    </ItemGroup>

</Project>
```
- In your `Directory.Build.props` or `.csproj` files, you add your Package Reference (Note: The `Version` attribute intentionally left out):  
  `<PackageReference Include="System.Text.Json" />`

**Comment by tintoy** [comment]
Interesting! Yeah I think we could support this (it’d  currently ignore any package elements that didn’t match the expected format). I’ll take a look at this tomorrow morning and see what would be involved 🙂

**Comment by tintoy** [comment]
Still looking into this (sorry, been pretty busy at work this week) 🙂

**Comment by loligans** [comment]
No problem, I appreciate you looking into this 😌

**Comment by tintoy** [comment]
Moving to #163.
