### ISSUE TITLE
C# Dev Kit Breaks

### ISSUE THREAD

**Issue by ProTip** [tintoy/msbuild-project-tools-vscode#113]
The required version of the C# Base Lang extension required by the pre-release of C# Dev Kit seems to break this. I have to disable in order for this to start working again. A shame since this is so incredibly handy.

**Comment by tintoy** [comment]
What behaviour are you seeing - are there errors in the output window, or is the extension just not being loaded when editing MSBuild project files?

**Comment by ProTip** [comment]
When I enable the C# extension `v2.0.248` the msbuild tools output just says it unloaded the project; no errors.

It's currently breaking syntax highlighting in `.csproj` files as well, so probably an issue with the C# extension itself..

**Comment by tintoy** [comment]
Thanks - I'll look into it when I get home 🙂

**Comment by ProTip** [comment]
Looks like this is being caused by C# extension re-associating the file type: dotnet/vscode-csharp#5860 . I will close for now as it looks like they are sorting it out..

**Comment by tintoy** [comment]
Thanks for reporting! I'll keep an eye on it anyway 🙂
