### ISSUE TITLE
Support using versions of MSBuild shipped with SDK Previews

### ISSUE THREAD

**Issue by baronfel** [tintoy/msbuild-project-tools-vscode#144]
Hello, thanks for this awesome tooling! I work on the .NET SDK and as such have a lot of preview SDK versions installed, including .NET 9 previews. When I run in this scenario, the MSBuild location code throws an exception with the following message:

```
System.Exception: Cannot locate MSBuild engine for .NET SDK v9.0.100. This probably means that MSBuild Project Tools cannot find the MSBuild for the current project instance. It did find the following version(s), though: [8.0.200, 8.0.101, 7.0.400, 7.0.312, 7.0.115, 6.0.418].
   at MSBuildProjectTools.LanguageServer.Utilities.MSBuildHelper.DiscoverMSBuildEngine(String baseDirectory, ILogger logger)
   at MSBuildProjectTools.LanguageServer.Program.Main()
[Error - 4:13:16 PM] Connection to server got closed. Server will not be restarted.
[Error - 4:13:16 PM] MSBuild Language Service client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:13:16 PM] Server process exited with code 1.
```

It would be awesome if prereleases could be opted into somehow for this tool!

**Comment by DoctorKrolic** [comment]
> I wolud say, "the best of both worlds" behavior can sound like this: it user has globally installed SDK of the requested version or above, use it, otherwise install a local SDK of the requested version. As far as I know, C# extension uses this strategy, but it seems to be a utility behavior, which I expect to be present in the runtime extension itself.

Found this logic in C# extension. They have [a whole class]() responsible for managing runtimes. As I already said, I think this is a utility behavior, so it might make sence to put this logic into the runtime extension itself.
@baronfel What's the vision of runtime extension team on this?
