### ISSUE TITLE
No compatible .NET runtime found

### ISSUE THREAD

**Issue by lonix1** [tintoy/msbuild-project-tools-vscode#150]
Problem started after upgrading to vscode-csharp `2.31.19` released yesterday.

When reopening vscode I get the normal popup:
> Initialising MSBuild project tools...

But it runs forever. So I opened the "C#" log which has this:
```
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 8.0.
```

I'm still on v7. Is that no longer supported?

dotnet 7.0.409
vscode 1.89.1 (latest)
c# extension 2.31.19 (latest)
msbuild extension 0.6.3 (latest)

**Comment by tintoy** [comment]
Yeah sorry, not sure what was going on there but glad to hear it eventually resolved itself!
