### ISSUE TITLE
Null response for empty completion requests

### ISSUE THREAD

**Issue by LucasBullen** [tintoy/msbuild-project-tools-vscode#17]
Request:
```
{
  "jsonrpc":"2.0",
  "id":"2",
  "method":"textDocument/completion",
  "params":{
    "textDocument":{
      "uri":"file:///home/lbullen/runtime-EclipseApplication/NewDotnetProject1/NewDotnetProject1.csproj"
    },
    "uri":"file:///home/lbullen/runtime-EclipseApplication/NewDotnetProject1/NewDotnetProject1.csproj",
    "position":{
      "line":0,
      "character":0
    }
  }
}
```
Response:
```
{
  "protocolVersion":"2.0",
  "id":"2",
  "result":null
}
```

Looking at the [LSP for completion-requests](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request), the expected response should be `CompletionItem[] | CompletionList`.

`null` is not accepted or else the protocol would look like the [Goto Definition Request Protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#goto-definition-request): `Location | Location[] | null`

**Comment by tintoy** [comment]
Ooh, that's interesting - my understanding was that null means "completions not supported here" (VSCode seems to show an empty completion list if I return `CompletionItem[]`, but no list at all if I return `null`). That signature comparison does seem compelling though.

If I start always returning non-`null` here it would break my extension (since I have to rely on "silently" triggering completion sometimes; VSCode may ask for completions, but shows nothing since I return null).

FWIW, my LSP client implementation is perfectly happy either way:

https://github.com/tintoy/dotnet-language-client/blob/master/src/LSP.Client/Clients/TextDocumentClient.Completions.cs#L32

How about if I add a feature flag to return empty completion lists instead of `null` - would that be good enough?

**Comment by tintoy** [comment]
Ok - after starting the language service, if you send it a "workspace/didChangeConfiguration" message 
 with `params` along the lines of:

```json
{
    "settings": {
        "msbuildProjectTools": {
            "language": {
                "enable": true,
                "disableHover": false,
                "logLevel": "Information",
                "experimentalFeatures": [
                    "empty-completion-lists"
                ]
            }
        }
    }
}
```

BTW, the full settings schema is:

```json
{
    "settings": {
        "msbuildProjectTools": {
            "language": {
                "enable": true,
                "disableHover": false,
                "logLevel": "Information",
                "trace": true,
                "seqLogging": {
                    "url": "http://localhost:5341/",
                    "apiKey": "KN3CFcqcWmsirb3ztL9g",
                    "logLevel": "Verbose"
                },
                "completionsFromProject": [
                    "Property",
                    "ItemType",
                    "ItemMetadata",
                    "Target",
                    "Task"
                ],
                "experimentalFeatures": [
                    "expressions",
                    "empty-completion-lists"
                ]
            },
            "nuget": {
                "newestVersionsFirst": true,
                "disablePrefetch": true
            }
        }
    }
}
```

**Comment by tintoy** [comment]
BTW, sorry for the slow response - I didn't get the notification until this morning, for some reason!

**Comment by LucasBullen** [comment]
Is there a possibility for the experimentalFeatures to be set within the initializationOptions of the `initialize` call? LSP4E does not support making `workspace/didChangeConfiguration` calls.

BTW, sorry for the _very_ slow response, was busy with other tasks

**Comment by tintoy** [comment]
No problem :)
Let me do an experiment or 2 - will need to see the server-side parameter type. Should be doable, or at worst I could make it an environment variable. Will give it a go as soon as I get to work (an hour and a half)

**Comment by tintoy** [comment]
Ok, yep, looks like I can do it - give me a couple of minutes. Do you need a new package, or can you run from source?

**Comment by tintoy** [comment]
Basically, just pass something like the following JSON in `InitializationOptions`:

```json
{
    "msbuildProjectTools": {
        "logging": {
            "level": "Information"
        },
        "nuget": {
            "newestVersionsFirst": true,
            "disablePrefetch": true
        },
        "experimentalFeatures": [
            "empty-completion-lists"
        ],
        "schemaVersion": 1
    }
}
```

**Comment by LucasBullen** [comment]
Perfect! That did it, no more errors on my end. [We will need a new package](https://github.com/eclipse/aCute/pull/93#issuecomment-330890898) if that is a possibility then we will be able to add your completion-suggestion work to aCute (Whoot!) and have the rest of the features functional once the initialization capabilities issue is solved.

**Comment by tintoy** [comment]
Woohoo! Ok, will put put out a new release sometime this morning then :)

**Comment by tintoy** [comment]
Ok, @LucasBullen, here you go - [v0.2.15](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.15)

**Comment by tintoy** [comment]
PS. Thanks for using this - it's great to see broader adoption :)

**Comment by tintoy** [comment]
BTW, not sure if you support [snippet-style completions](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md); if not, some types of completions (e.g. new elements) may not work correctly yet. Let me know if this is the case, and I can either offer a setting to turn off unsupported suggestion types (quick) or implement a fall-back to regular-style completions (may take a while, but definitely doable, although the UX is slightly less pleasant without snippet-style support we have no control over cursor positioning after inserting the completion).

**Comment by LucasBullen** [comment]
Thanks! Yes lsp4e has snippet-style completion support and the new cut works great.
