### ISSUE TITLE
Be able to filter out pre-release packages in the auto-complete drop-down

### ISSUE THREAD

**Issue by ebekker** [tintoy/msbuild-project-tools-vscode#18]
Is it possible to add a way to filter whether you want to include or not pre-release package versions in the auto-complete drop-down.  I'm not sure how much UI control and flexibility is possible in the drop-down (i.e. is it a built-in component of VSCode or completely custom?), but maybe just a small section down at the bottom of the drop-down that has a checkbox for Pre-Release?

(BTW, love your tool!)

**Comment by tintoy** [comment]
Thanks :)

I don't have control of the UI, unfortunately, but I could define a command to toggle pre-release packages on and off that you could bind to a keyboard short-cut; would that suffice?

**Comment by ebekker** [comment]
Oh I see -- yeah, I guess that makes sense, it's just like auto-complete for any language, you only have the context of where you are in the *code* to make decisions, so there really isn't any way to flag pre-release on a per-package/per-line basis, only wholesale for the current environment.

Yes, a toggle would be great, thanks!

**Comment by ebekker** [comment]
Does the LSP have the ability to distinguish different categories or types of auto-completion entries?  I'm thinking, like when you have an auto-complete for an identifier in other languages, like C#, you get different member types (methods, properties, fields, etc.).

Now it doesn't appear that Code gives you an easy way to filter by types -- I know that's something that was recently added to full VS, and has been in add-ons like ReSharper for a while, so maybe that will be a future enhancement in Code itself.

So one way to at least distinguish those items would be to categorize release vs. pre-release.

Just thinking out loud...  The toggle would be great!

**Comment by tintoy** [comment]
> Does the LSP have the ability to distinguish different categories or types of auto-completion entries?

[Not exactly](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_completion), but it's a little open-ended. In the end, as you say VS Code doesn't support it yet, but it's something they may be able to add. They're pretty responsive to requests, I've noticed ;-)

No problem - give me an hour or so and I'll add it.

**Comment by tintoy** [comment]
Ok, that took slightly longer than expected (unrelated issue) but it's working now. Will publish a new version in half an hour or so :)

**Comment by tintoy** [comment]
Ok, @ebekker - can you give [v0.2.9](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.9) a try? You can just upgrade it from within VS Code's extensions window.

The command to invoke is `NuGet: Toggle pre-prelease` (you can bind a keyboard shortcut to `msbuildProjectTools.toggleNuGetPreRelease`).

**Comment by ebekker** [comment]
Wow, talk about responsive!

**Comment by ebekker** [comment]
Weird -- when I bring up the command palette, and start typing `Nuget`, it immediately auto-finds the `Nuget: Toggle pre-prelease` command, but when I invoke it, I get the error:

`command 'msbuildProjectTools.toggleNuGetPreRelease' not found`

**Comment by ebekker** [comment]
Actually, the whole extension doesn't seem to be working for me now -- it's not resolving packages at all now.

**Comment by tintoy** [comment]
Ok, just installed the extension from the gallery and something seems to be broken (which is odd, because it works when I run it from source). Sorry for the inconvenience, I'll figure it out and get back to you.

**Comment by tintoy** [comment]
Ah, ok, figured out the problem. I had to change the configuration schema slightly, and wound up removing the defaults for some configuration items. It works locally because I _do_ have values for those settings, but you probably don't. I'm putting out a new release now.

Again, sorry for the inconvenience and delay (I'm in AU if you're wondering about the delay; just woke up about half an hour ago 😄).

**Comment by tintoy** [comment]
Ok @ebekker - I've tested [v0.2.10](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.10) on a clean install and it works correctly as far as I can tell. Would you mind updating and having another go?

**Comment by ebekker** [comment]
You rock!  Works great, thank you!

**Comment by tintoy** [comment]
Awesome, thanks for sticking with it :)
