### ISSUE TITLE
Improve performance of task completions

### ISSUE THREAD

**Issue by tintoy** [tintoy/msbuild-project-tools-vscode#23]
This is still slower than I'd like (seems to have a floor of around 200ms, which is way too long).

Consider scanning task assembly metadata in the background and only using the cached results (i.e. no on-demand scanning).

**Comment by DoctorKrolic** [comment]
Can you check whether this is an issue in dev builds with in-process task scanning work done and close if this is no longer relevant? I cannot do this myself since I don't know how you measured it in the first place

**Comment by tintoy** [comment]
Sure, will do - I'll take a look sometime this evening.

**Comment by tintoy** [comment]
Yep, this issue can be closed, now - the latency introduced by spawning another process is gone, so this is no longer an issue.
