### ISSUE TITLE
More clearly split Language Server and VSCode extension

### ISSUE THREAD

**Issue by mickaelistria** [tintoy/msbuild-project-tools-vscode#24]
The language server in this repo is reusable out of vscode and doesn't require node nor typescript to build/run. In order to make it easier for other IDEs to consume it, it would be great to more clearly separate the pure LSP parts and the VSCode parts so consumers could pick only the LSP part.
cc @LucasBullen

**Comment by tintoy** [comment]
Thanks for reminding me! Been meaning to do this for a while now - will have a go at it this weekend :)

**Comment by tintoy** [comment]
I'm going to have a crack at this sometime today - new repo will be https://github.com/tintoy/msbuild-project-tools-server

**Comment by tintoy** [comment]
@mickaelistria - what format is convenient for releases here? A `.zip` file?

**Comment by mickaelistria** [comment]
Zip are usually good. That's what OmniSharp-rosltn provides IIRC.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community
Elected Committer Representative at the Eclipse Foundation
<https://www.eclipse.org/org/> board of directors

**Comment by tintoy** [comment]
Ok - can do, am about halfway now; will finish it off over the weekend :)

**Comment by tintoy** [comment]
@mickaelistria - good to go now; the CI build automatically produces [GitHub releases](https://github.com/tintoy/msbuild-project-tools-server/releases) with `.zip` files for the server and its task-reflection tool.

Sorry it took so long, other stuff just kept getting in the way :)

CC:  @LucasBullen

**Comment by tintoy** [comment]
@mickaelistria - the split is complete, so I'm closing this issue. Feel free to reopen it if you still have issues or requirements that haven't been addressed :)
