### ISSUE TITLE
Please stop auto focussing the output window when I hover in a proj file 

### ISSUE THREAD

**Issue by NinoFloris** [tintoy/msbuild-project-tools-vscode#25]
Please stop auto focussing the output window when I hover in a proj file.

https://cl.ly/0N172K3Y0403

**Comment by tintoy** [comment]
Hi.

Sorry, it's not supposed to do that (I can imagine it'd be annoying); can you confirm that `trace` is `false` or not present in your VSCode settings?

```json
"msbuildProjectTools": {
    "logging": {
        "trace": false
    }
}
```

**Comment by NinoFloris** [comment]
Thanks for your quick reply :)

Yes this is my config:
<img width="349" alt="screen shot 2017-12-11 at 23 55 36" src="https://user-images.githubusercontent.com/4218809/33858147-d0fb4930-dece-11e7-972e-26a807002b4b.png">

Works well otherwise though, great work!

**Comment by tintoy** [comment]
No worries - I think I see the problem :)

If I post a VSIX package here would you be willing to try it out and see if it fixes your problem?

**Comment by NinoFloris** [comment]
Sure no problem, I know how to by now ;)

**Comment by tintoy** [comment]
Ok, give me a sec - building one now.

**Comment by tintoy** [comment]
Ok - just unzip the VSIX and install into VS Code:

[msbuild-project-tools-0.2.17.zip](https://github.com/tintoy/msbuild-project-tools-vscode/files/1549673/msbuild-project-tools-0.2.17.zip)

**Comment by NinoFloris** [comment]
Still happens :/

**Comment by tintoy** [comment]
Hmm, that's interesting - what version of VS Code are you working with? I've just tried it in both VS Code and VS Code Insiders and it no longer happens on either unless `trace` is set to `true` :-/

**Comment by NinoFloris** [comment]
Yep edited previous comment :) thanks for the help

**Comment by tintoy** [comment]
Phew! No problem - I'll create a proper release shortly, then you can install from the gallery (I think it'd automatically upgrade but I can't remember anymore if that's true).

**Comment by tintoy** [comment]
Ok, @NinoFloris - the new release is up in the marketplace. Pretty sure you won't have to upgrade the package by hand (since the extension Ids still match up) but if you find you're not seeing expected updates then you might need to just remove the extension and install it from the gallery.

Glad you like it, and sorry again for the annoyance :)

**Comment by tintoy** [comment]
(that's [v0.2.17](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.17))
