### ISSUE TITLE
Any plan on code snippets for MSBuild project file?

### ISSUE THREAD

**Issue by doggy8088** [tintoy/msbuild-project-tools-vscode#28]
Hi,

Do you have any plan on code snippets for MSBuild project file?  Any ideas?

**Comment by tintoy** [comment]
Hi - are there any you'd particularly like to see? I'm open to the idea :)

**Comment by doggy8088** [comment]
@tintoy Yes, I have tons of ideas for this. 😄 

* For ASP.NET Core 2.0 apps, there are some common patterns that are very often to add manually.
  - Metapackage for ASP.NET Core
    ```
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
      </ItemGroup>
    ```
  - `dotnet-watch` tool
    ```
      <ItemGroup>
          <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
      </ItemGroup>
    ```
   - When deploy ASP.NET Core to IIS, you need to add this one.
    ```
      <PropertyGroup>
        <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
      </PropertyGroup>
    ```

* For .NET Core & NuGet package
  - There are some properties need to be filled when you need to pack as a NuGet package
    ```
	  <PropertyGroup>
	    <Company>$CompanyName$</Company>
	    <Authors>$Author$</Authors>
	    <Version>$Version$</Version>
	    <Description>$Description$</Description>
	    <IncludeSymbols>true</IncludeSymbols>
	    <IncludeSource>true</IncludeSource>
	    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	  </PropertyGroup>
    ```
  - For the multi-targeting framework in .NET Standard project
    ```
	  <ItemGroup Condition="'$(TargetFramework)' == '$moniker$'">
	    <Reference Include="$NuGetPackageName$" />
	  </ItemGroup>
    ```

There are some other frameworks such as Entity Framework Core.  There are some tooling support need to change `*.csproj` manually.

What do you think? 😃

**Comment by tintoy** [comment]
Those are great ideas! 

Would you like to open a PR or would you prefer me to add them? I'm happy to do either 😀

**Comment by doggy8088** [comment]
@tintoy Can I just put my snippets into https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/snippets/msbuild-project.json , then you do the following works?

**Comment by tintoy** [comment]
Sure that's fine, I can take it from there.

**Comment by doggy8088** [comment]
@tintoy I've been tested.  All works.  Please take a look.  Thanks. 😄

**Comment by tintoy** [comment]
@doggy8088 - it's good to go:

https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.21

Thanks again for your contribution! Feel free to add any other snippets you come up with :wink:

**Comment by doggy8088** [comment]
@tintoy I installed this version.  The code snippets looks not working.  Do you know why?

![image](https://user-images.githubusercontent.com/88981/35470839-9838733e-038b-11e8-9043-aa36378fd0ef.png)

**Comment by tintoy** [comment]
Have you [changed the language to MSBuild](https://github.com/tintoy/msbuild-project-tools-vscode/#file-extensions)?

**Comment by tintoy** [comment]
Here's what I see:

![image](https://user-images.githubusercontent.com/1646284/35470900-a8dfd6e0-03a5-11e8-822f-57c670e0c429.png)

**Comment by doggy8088** [comment]
I opened my *.csproj file, the default language mode is "XML".   After I switch language mode to MSBuild. 
 Everything is OK.  But why my default is XML?  What else I need to configure?

**Comment by doggy8088** [comment]
After I set the **"files.associations"** in my user settings.  The default language mode has been changed to msbuild now.  Problem solved.  👍 

```
    "files.associations": {
        "*.csproj": "msbuild"
    }
```

**Comment by tintoy** [comment]
Yeah - the readme shows how to do that, but I was nervous about automatically taking over people's file associations:)
