### ISSUE TITLE
Extension Package (VSIX) size is bit big!

### ISSUE THREAD

**Issue by Nirmal4G** [tintoy/msbuild-project-tools-vscode#37]
The current package contains entire source code tree and including the pdb/xml files which causes the package size to be >10Mb!

Is this intended?
If so Why?

If not, Can we not include unnecessary files, I know the license states that you include source distribution but that's why we have git/GitHub and commit hashes right?

Would be easier to tag'em and put the hash in the ChangeLog?

**Comment by tintoy** [comment]
Hmm, not really intentional, although for a nodejs app we do have to include `node_modules`, which probably blows out the size a bit... We certainly don't need to include any C# source code, so feel free to open a PR to modify `.vscodeignore` as required :)

**Comment by tintoy** [comment]
From memory, all that the extension package needs to contain is `package.json`, `node_modules`, `help/`, and everything under `out/`.

**Comment by tintoy** [comment]
Ok - that's more than halved it to around 5MB :)

**Comment by tintoy** [comment]
And that's probably all we can strip out. The PDB files are high-value, and take up comparatively little space (none are larger than 50KB).

**Comment by Nirmal4G** [comment]
I got it around 5.3Mb when I was working SDK docs concept (BTW It's almost done), that's why I asked.

Anyway thanks!

**Comment by tintoy** [comment]
Yep, thanks! About to publish v0.2.38 to the marketplace :)
