### ISSUE TITLE
Check if it's still possible to render file-system hyperlinks in hover tooltips

### ISSUE THREAD

**Issue by tintoy** [tintoy/msbuild-project-tools-vscode#40]
Currently, they are rendered as raw markdown (e.g. `[link](file://C:/Foo/bar.targets)`) instead of hyperlinks.

May relate to Microsoft/vscode#33577.

**Comment by DoctorKrolic** [comment]
This is no longer reproducible, closing:
![Code_g1a4tVTx9J](https://github.com/tintoy/msbuild-project-tools-vscode/assets/70431552/e89bf610-71a3-446d-bd38-833b303706e3)
