### ISSUE TITLE
Invalid static method invocation syntax

### ISSUE THREAD

**Issue by NN---** [tintoy/msbuild-project-tools-vscode#41]
Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget)

**Comment by tintoy** [comment]
Hi - what version of the extension are you using, and in which file does the error occur?

I think this was fixed at the end of last year (see issue #26 for details).

**Comment by NN---** [comment]
I reinstalled the extension and not it doesn't show any problem.
