### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Othniel10** [tintoy/msbuild-project-tools-vscode#49]
- Issue Type: `Performance`
- Extension Name: `msbuild-project-tools`
- Extension Version: `0.2.53`
- OS Version: `Windows_NT x64 10.0.18305`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\hp\tintoy.msbuild-project-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by tintoy** [comment]
Thanks for reporting this - I’ll take a look tomorrow morning :)

**Comment by tintoy** [comment]
Hi - can you attach the file mentioned in your issue so I can take a look?

**Comment by tintoy** [comment]
Hi - I'm going to close this for now, but feel free to reopen it if the problem occurs again.
