### ISSUE TITLE
System.InvalidOperationException: Cannot determine base directory for .NET Core

### ISSUE THREAD

**Issue by ar0311** [tintoy/msbuild-project-tools-vscode#50]
Seems to be a dupe of #43

System.InvalidOperationException: Cannot determine base directory for .NET Core (check the output of 'dotnet --info').
   at ProjectCollection MSBuildProjectTools.LanguageServer.Utilities.MSBuildHelper.CreateProjectCollection(string solutionDirectory, DotNetRuntimeInfo runtimeInfo, Dictionary<string, string> globalPropertyOverrides) in /////

Fresh install on Ubuntu 18.04 with only C# extension and this one installed.

Output of dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by tintoy** [comment]
Can you include the rest of the error output, please? The full stack trace if possible :)

**Comment by ar0311** [comment]
tarting MSBuild language service...
MSBuild language service is running.
[Info  - 2:07:47 pm] 1 package sources configured for project "/home/adam/Documents/repos/RavenDB.Identity/Sample/Sample.csproj".
[Info  - 2:07:47 pm]   Locally-configured package source "nuget.org" (v3) => https://api.nuget.org/v3/index.json
[Error - 2:07:51 pm] Error loading MSBuild project '"/home/adam/Documents/repos/RavenDB.Identity/Sample/Sample.csproj"'.
System.InvalidOperationException: Cannot determine base directory for .NET Core (check the output of 'dotnet --info').
   at ProjectCollection MSBuildProjectTools.LanguageServer.Utilities.MSBuildHelper.CreateProjectCollection(string solutionDirectory, DotNetRuntimeInfo runtimeInfo, Dictionary<string, string> globalPropertyOverrides) in /home/adam/Documents/repos/RavenDB.Identity/D:\Development\github\tintoy\msbuild-project-tools-vscode\lib\server\src\LanguageServer.Common\Utilities\MSBuildHelper.cs:line 81
   at ProjectCollection MSBuildProjectTools.LanguageServer.Utilities.MSBuildHelper.CreateProjectCollection(string solutionDirectory, Dictionary<string, string> globalPropertyOverrides) in /home/adam/Documents/repos/RavenDB.Identity/D:\Development\github\tintoy\msbuild-project-tools-vscode\lib\server\src\LanguageServer.Common\Utilities\MSBuildHelper.cs:line 49
   at bool MSBuildProjectTools.LanguageServer.Documents.MasterProjectDocument.TryLoadMSBuildProject() in /home/adam/Documents/repos/RavenDB.Identity/D:\Development\github\tintoy\msbuild-project-tools-vscode\lib\server\src\LanguageServer.Engine\Documents\MasterProjectDocument.cs:line 152

**Comment by tintoy** [comment]
Thanks! I’ll try to reproduce the problem and see what I can find :)

**Comment by tintoy** [comment]
Hmm - I added a test that uses the input specified above, but it seems to work rather than fail (the path is correctly determined).

I'm wondering if it might be a unix-style newlines issue; could you try running:
`dotnet --info > $PWD/dotnetinfo.txt`
and attaching the file to this issue?

**Comment by ar0311** [comment]
[dotnetinfo.txt](https://github.com/tintoy/msbuild-project-tools-vscode/files/3180113/dotnetinfo.txt)

**Comment by tintoy** [comment]
Thanks! Will download it and give it a try now.

**Comment by tintoy** [comment]
Hmm - I tried running the tests with the output you supplied and they still work fine (base path correctly detected as `/usr/share/dotnet/sdk/2.2.203/`).

I'll see if I can think of anything else but so far I can't see what else could be going wrong :-/

Could you try creating a new .NET Core console app (`dotnet new console`) and pasting this source code into the end of `Program.cs`:

https://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.Common/Utilities/DotNetRuntimeInfo.cs

Then in `Program.cs`, add the following code:

```csharp
static void Main()
{
    Console.WriteLine("BaseDirectory: '{0}'",
        DotNetRuntimeInfo.GetCurrent("/the/directory/containing/your/solution/file").BaseDirectory
    );
}
```

If nothing else it will give us a starting point for troubleshooting :)

**Comment by tintoy** [comment]
Actually, there might be one other thing you can try as well:

Try changing the `MSBuild Project Tools > Logging Level` setting in VS Code to `Verbose`, then trying to re-open your solution directory in VS Code. The logging (shown in the `Output` window's `MSBuild Project Tools` pane) might show some useful information about what's going on.

**Comment by ar0311** [comment]
Can't repro, have updated SDK and seems to be gone. Thanks for the detailed troubleshooting steps.
