### ISSUE TITLE
Add .msbuild extension as MSBuild known file

### ISSUE THREAD

**Issue by NN---** [tintoy/msbuild-project-tools-vscode#51]

**Comment by tintoy** [comment]
Hi - this should be easy enough to do; I will have a look tomorrow morning :)

**Comment by tintoy** [comment]
Ok, done. I'll try to get a new build out sometime today.

**Comment by doggy8088** [comment]
Is this one should be closed?

**Comment by tintoy** [comment]
Yes, thanks for reminding me :)

Work has been a little crazy recently so I haven’t had much time to work on this stuff but Holidays start today so I’ll have a little more time.
