### ISSUE TITLE
Prefer descending over ascending in package versions

### ISSUE THREAD

**Issue by savpek** [tintoy/msbuild-project-tools-vscode#6]
Nice tool!

Is it possible to change order of package versions so that newest is at top on autocomplete? Currently it shows oldest first which is bit strange.

![image](https://user-images.githubusercontent.com/481896/29741837-0c36a96e-8a7d-11e7-8c4d-82ef97cf1b4e.png)

**Comment by tintoy** [comment]
Thanks, glad you like it :) 

You are right - it makes much more sense to put newer versions first; give me half an hour and I'll put out a new release.

**Comment by tintoy** [comment]
Hi - I've just released [v1.1.11](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.1.11) where the default behaviour is now to sort package versions in descending order (according to SemVer 2.0 rules). Would you mind updating your extension in VSCode and letting me know if you're happy with the behaviour?

**Comment by savpek** [comment]
Perfect 👍

**Comment by tintoy** [comment]
Thanks for the feedback, BTW :D

**Comment by tintoy** [comment]
(good to know people are finding it useful!)
