### ISSUE TITLE
Missing GenerateDocumentationFile property

### ISSUE THREAD

**Issue by doggy8088** [tintoy/msbuild-project-tools-vscode#60]
There is a common property called `<GenerateDocumentationFile>true</GenerateDocumentationFile>` which is missing from this extension. Is it possible to add this?

![image](https://user-images.githubusercontent.com/88981/71189973-a70d0380-22be-11ea-8e19-f445db263e78.png)

**Comment by tintoy** [comment]
Sure, should be easy enough to add :)

**Comment by doggy8088** [comment]
Can you teach me? So I can make PR for you.

**Comment by tintoy** [comment]
Sure, thanks - I’ll write up some instructions tomorrow morning :)

**Comment by tintoy** [comment]
This is the file you’ll want to modify:

https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/help/properties.json
