### ISSUE TITLE
Unable to start MSBuild language server

### ISSUE THREAD

**Issue by sharadkeshari** [tintoy/msbuild-project-tools-vscode#64]
Issue Type: <b>Bug</b>

whenever starting vscode

Extension version: 0.3.3
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

**Comment by tintoy** [comment]
Are there any messages in the output window from MSBuild Project tools?

**Comment by softlion** [comment]
I have the same issue. I can't see any message, but there is no MSBUILD language available beside XML.

**Comment by tintoy** [comment]
Is there an “MSBuild Project Tools” section in the output window?

**Comment by agolks** [comment]
found this in the corresponding output window:
`It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]`
will try to solve it and leave a note

**Comment by agolks** [comment]
i've installed [latest 3.1 version](https://dotnet.microsoft.com/download/dotnet-core/3.1) now it works:
```
Starting MSBuild language service...
MSBuild language service is running.
```

**Comment by DoctorKrolic** [comment]
@tintoy Situations like this should no longer occur after https://github.com/tintoy/msbuild-project-tools-vscode/pull/112. Can you close this issue then?
