### ISSUE TITLE
Hovering over PackageReference elements to show restored version always displays "Not restored"

### ISSUE THREAD

**Issue by mario-d-s** [tintoy/msbuild-project-tools-vscode#75]
It's as simple as the title says. When enabling the extension I can hover the cursor over a `<PackageReference>` element in a `.csproj` file, and the tooltip says `State: not restored` no matter what I try.

To verify it's not due to any complexity of our existing solution, I did:

1. `dotnet new console`
2. `dotnet package add newtonsoft.json`
3. `dotnet restore`

`newtonsoft.json` state is "not restored" according to this extension.

**Comment by mario-d-s** [comment]
Hmm, for some reason this is now working for me. Could be I needed to restart VS Code.
The C# extension is also giving me trouble a lot, sometimes needing VS Code restarts.
I'll close this issue for now.

**Comment by tintoy** [comment]
Sorry you’re having trouble. Feel free to reopen if it happens again 🙂
