### ISSUE TITLE
Add extension to open-vsx

### ISSUE THREAD

**Issue by pm4rcin** [tintoy/msbuild-project-tools-vscode#78]
Hi, please consider adding extension to [open-vsx](https://open-vsx.org) so people who use VSCodium could easily use it.

**Comment by tintoy** [comment]
Hi - thanks, I’ll look into this 🙂

**Comment by pm4rcin** [comment]
Any progress on that? :)

**Comment by tintoy** [comment]
Sorry, work has been pretty crazy this week! I’ll try to get this done today :)

**Comment by tintoy** [comment]
Ok, published 🙂

https://open-vsx.org/extension/tintoy/msbuild-project-tools

Can you let me know if that works for you? It's the same package that's currently published in VSCode extension gallery.

**Comment by pm4rcin** [comment]
I've tested it and it works. Thank you :)

**Comment by pm4rcin** [comment]
Hi, @tintoy the extension is outdated on open-vsx. Could you push the newest version? Also it would be a good idea to make publishing via github actions.

**Comment by tintoy** [comment]
Thanks for the reminder!

I've now published it, but it may take a little while to become visible :)

**Comment by vindicatorr** [comment]
I see you have an Azure pipeline to publish to the marketplace.
Adding one for open-vsx would be nice even though the version there is currently only 1 revision old.

**Comment by tintoy** [comment]
Thanks, that's not a bad idea; I'll look into this once the current batch of changes (`.slnx` support) are ready.
