### ISSUE TITLE
Can I set the language server to use .NET 6 Preview?

### ISSUE THREAD

**Issue by niem94** [tintoy/msbuild-project-tools-vscode#82]
I'm on apple silicon, so running .NET 5 is not an option for me, and I would really like this extension to work. Is it possible to set the language server to use .NET 6 Preview?

**Comment by tverboon** [comment]
@tintoy: For me your extension `v0.4.0-preview1` is working with `6.0.100-preview.7.21379.14` on a Mac. The most important feature for me is the NuGet autocomplete for versions. Thanks!

**Comment by tintoy** [comment]
Great! I won’t publish that version to the gallery yet (since it will force everyone to upgrade to 6 before they can use it) but I will keep any eye on 6 and as soon as it hits RTM I’ll build a new version and publish it to the gallery :)

**Comment by JohnCampionJr** [comment]
Thank you for this - dumb question - how do I use this with VS Code without the gallery?

**Comment by tintoy** [comment]
In the extensions tab in VS Code there is a little “…” menu button in the top right. Under that menu you’ll find an option to install the VSIX package (you may need to unzip it first).

🙂

**Comment by tintoy** [comment]
Published v0.4.1 to the VS Gallery (now targets .NET 6).
