### ISSUE TITLE
[Question] Using extension with .NET5

### ISSUE THREAD

**Issue by lonix1** [tintoy/msbuild-project-tools-vscode#95]
Sorry if this is a stupid question, but I after reading the docs and some other issues, I can't find the answer.

I'm still using .NET5 and don't plan to upgrade to 6 anytime soon. Can I somehow use the latest version of this extension, or am I stuck with 0.3.15?

(I tried installing the latest version but it complained I was missing net6, so I rolled back. But I read somewhere in the docs that I can "target net5" even though the extension is net6... but I don't understand how to do that?)

**Comment by tintoy** [comment]
Hi - I haven't tried that particular combination myself, but you shouldn't need to upgrade your SDK to 6.0.x; only the [.NET Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) (which installs side-by-side with other versions of .NET Core) to run the latest version(s) of the extension / language service.

**Comment by tintoy** [comment]
In other words, visit https://dotnet.microsoft.com/en-us/download/dotnet/6.0 and install the package labeled `.NET Runtime 6.0.x` (or `.NET Desktop Runtime 6.0.x` / `ASP.NET Core Runtime 6.0.x`, if you need to run other apps that were built against .NET 6) and you should be good to go.
